-- | Canonical forms — TAPL Theorem 8.3.1, both halves.
--
-- @examples\/canonical.thena@ is a **companion to the determinacy example**: the
-- same terms, with the typing relation that file does not have. Where
-- determinacy is 278 surface lines and generated by @examples\/determinacy.py@,
-- this one is 127 and **written by hand** — which is the point of having it, so
-- that the suite contains a substantial proof nobody generated.
--
-- **The two statements are asserted, not just the load**, for the determinacy
-- suite's reason: a proof of something weaker would pass a golden of the load's
-- own output without a word.
module Thena.CanonicalTests (tests) where

import Data.ByteString.Builder (stringUtf8, toLazyByteString)
import Test.Tasty (TestTree, testGroup)
import Test.Tasty.Golden (goldenVsString)
import Test.Tasty.HUnit (testCase, (@?=))

import Thena.Core.Term (GlobalName (..))
import Thena.Driver (Session (..))
import Thena.Engine (Machine (..))
import Thena.Global.Env (Definition (..), lookupDefinition)
import Thena.Repl (startingSession, loadProofFile, renderCore)

target :: FilePath
target = "examples/canonical.thena"

tests :: TestTree
tests =
  testGroup
    "canonical forms — TAPL 8.3.1"
    [ goldenVsString "canonical" "test/golden/canonical.golden" $ do
        (s, problems) <- startingSession
        (_, out) <- loadProofFile s target
        pure (toLazyByteString (stringUtf8 (unlines (problems ++ out))))

      -- **The bool half.** A well-typed value of type @bool@ is @true@ or
      -- @false@ — which is what lets an @if@ take a step, and is why TAPL proves
      -- this before progress.
    , testCase "a well-typed boolean value is true or false" $ do
        st <- statementOf "canonicalBool"
        st @?= Just "∀ (v : Term) -> Value v -> HasType v bool \
               \-> Or (Eq {0} Term v true) (Eq {0} Term v false)"

      -- **The nat half**, and it is the one that carries the numeric-value
      -- predicate the determinacy example already had.
    , testCase "and a well-typed numeric value really is one" $ do
        st <- statementOf "canonicalNat"
        st @?= Just "∀ (v : Term) -> Value v -> HasType v nat -> NV v"

      -- The three inversion lemmas underneath them, stated so that a proof
      -- weakened into vacuity would show.
    , testCase "true is not a natural number" $ do
        st <- statementOf "trueNotNat"
        st @?= Just "HasType true nat -> Empty {0}"

    , testCase "and a numeric value is not a boolean" $ do
        st <- statementOf "nvNotBool"
        st @?= Just "∀ (t : Term) -> NV t -> HasType t bool -> Empty {0}"
    ]
  where
    statementOf n = do
      (s, _) <- startingSession
      (s', _) <- loadProofFile s target
      pure ( renderCore (names (sessionMachine s')) [] . definitionType
               <$> lookupDefinition (GlobalName n) (globals (sessionMachine s')) )
