{
-- | The Happy grammar for the core and development languages (§2.6, §2.7).
--
-- Four start symbols rather than one, because the driver always knows which of
-- four things it is about to read and a single grammar covering all of them
-- would be ambiguous:
--
--   * 'parseTerm' — a term or a development, as a 'Raw' (§2.6).
--   * 'parseNameAndType' — @x : S@, for the commands that name a new binding.
--   * 'parseData' — a @data@ declaration, as a 'RawData' (§2.7, phase 6).
--   * 'parseEquation' — @Ξ ⊢ s ≟ t : T@, as a 'RawConstraint' (§3.3, phase 9).
--
-- Their types are generated by Happy from the @%name@ directives below, so
-- Haddock has nowhere to attach per-function documentation and reports this
-- module as under-documented. That is a property of the tool, not a gap.
--
-- The parser is deliberately shallow. It produces names, never resolved
-- variables, and it does no shape checking beyond what the grammar enforces —
-- both are "Thena.Syntax.Resolve"'s job (§2.5).
module Thena.Syntax.Parser
  ( -- * Errors
    ParseError (..)

    -- * Entry points
  , parseTerm
  , parseNameAndType
  , parseData
  , parseEquation
  , parseRule
  , parseRules
  ) where

import Thena.Syntax.Concrete
  ( Raw (..)
  , RawBinder (..)
  , RawConstraint (..)
  , RawConstructor (..)
  , RawData (..)
  , RawInstr (..)
  , RawOp (..)
  , RawOperand (..)
  , RawRule (..)
  )
import Thena.Syntax.Lexer (Located (..), Pos, Token (..))
}

%name parseTerm Term
%name parseNameAndType NameAndType
%name parseData Data
%name parseEquation Equation
%name parseRule Rule
%name parseRules RuleFile
%tokentype { Located Token }
%monad { Either ParseError }
%error { parseError }

%token
  'λ'     { Located _ TLambda }
  '∀'     { Located _ TForall }
  '->'    { Located _ TArrow }
  '('     { Located _ TLParen }
  ')'     { Located _ TRParen }
  '{'     { Located _ TLBrace }
  '}'     { Located _ TRBrace }
  ';'     { Located _ TSemi }
  ':'     { Located _ TColon }
  '='     { Located _ TEquals }
  '?'     { Located _ TQuery }
  '≐'     { Located _ TGuessed }
  '▸'     { Located _ TPending }
  '⊢'     { Located _ TTurnstile }
  '≟'     { Located _ TEquate }
  '[|'    { Located _ TOpenQuote }
  '|]'    { Located _ TCloseQuote }
  let     { Located _ TLet }
  in      { Located _ TIn }
  elim    { Located _ TElim }
  where   { Located _ TWhere }
  rule    { Located _ TRule }
  when    { Located _ TWhen }
  then    { Located _ TThen }
  ':-'    { Located _ TNeck }
  num     { Located _ (TNumber $$) }
  univ    { Located _ (TUniverse $$) }
  ident   { Located _ (TIdent $$) }

%right '->'

%%

Term :: { Raw }
  : 'λ' Binders '->' Term                          { RawLam (reverse $2) $4 }
  | '∀' Binders '->' Term                          { RawPi (reverse $2) $4 }
  | let ident '=' Term ':' Term in Term            { RawLet $2 $4 $6 $8 }
  | let '?' ident ':' Term in Term                 { RawClaim $3 $5 $7 }
  | let '?' ident ':' Term '≐' '(' Term ')' in Term
                                                   { RawGuess $3 $5 $8 $11 }
  | Constraint '▸' Term                            { RawPending $1 $3 }
  | '[|' Term '|]'                                 { RawQuote $2 }
  | elim ident '(' Atoms ')' Atom '(' Atoms ')' '(' Atoms ')' Atom
      { RawElim $2 (reverse $4) $6 (reverse $8) (reverse $11) $13 }
  | App '->' Term                                  { RawArrow $1 $3 }
  | App                                            { $1 }

-- The argument of @:convert@ (§9, phase 8). Two terms and the @≟@ that §2.7
-- already spells a constraint's two sides with, so the separator is not a new
-- piece of notation — it is the one the user chose for exactly this question,
-- asked without a context or a type.
Equation :: { (Raw, Raw) }
  : Term '≟' Term                          { ($1, $3) }

-- The argument of @assume@ and @claim@ (§2.4's "commands are the op vocabulary
-- spelled out"). The nameless form is the one that makes the op ask (§7.5).
NameAndType :: { (Maybe String, Raw) }
  : ident ':' Term                         { (Just $1, $3) }
  | ':' Term                               { (Nothing, $2) }

-- The argument of @data@ (§2.7's grammar, extended; decided by the user
-- planning phase 6). @data@ itself is not a token: the driver splits the first
-- word off the line before the lexer sees anything, which is what keeps @data@
-- a perfectly good identifier (§2.4).
--
-- Parameters are the binder groups left of the @:@; indices are the arrow
-- prefix of the type right of it, which must end in a universe. That is the
-- split §3.7 requires disambiguated, made syntactic.
Data :: { RawData }
  : ident MaybeBinders ':' Term where '{' Constructors '}'
                                           { RawData $1 (reverse $2) $4 (reverse $7) }

MaybeBinders :: { [RawBinder] }
  :                                        { [] }
  | Binders                                { $1 }

-- A datatype with no constructors is legal and useful: @Empty@ (§3.7).
Constructors :: { [RawConstructor] }
  :                                        { [] }
  | SomeConstructors                       { $1 }

SomeConstructors :: { [RawConstructor] }
  : Constructor                            { [$1] }
  | SomeConstructors ';' Constructor       { $3 : $1 }

Constructor :: { RawConstructor }
  : ident ':' Term                         { RawConstructor $1 $3 }

-- The rule language (§8, phase 21). @:-@ separates the head — the name and its
-- parameters — from the conditions and the body, and the space on either side
-- of it is deliberately unused: pattern matching on the focus and on the goal
-- is coming and will attach to the head (DECIDED by the user 2026-08-25).
--
-- @when@ is optional, because a rule may apply everywhere; @then@ is not,
-- because a rule with no body does nothing. Test words and op words are
-- @ident@s and not tokens — see 'Thena.Syntax.Concrete.RawRule'.
-- A whole rule-base file, less its header line. Rules may span lines — DECIDED
-- by the user 2026-08-25 — so the file is parsed whole rather than split, and
-- what ends a rule is the next 'rule' keyword or the end of input. Nothing in
-- 'Instr' can begin with 'rule', so no terminator is needed.
RuleFile :: { [RawRule] }
  : Rules                                  { reverse $1 }

Rules :: { [RawRule] }
  :                                        { [] }
  | Rules Rule                             { $2 : $1 }

Rule :: { RawRule }
  : rule ident Params ':-' Tests then Body   { RawRule $2 $3 $5 (reverse $7) }

Params :: { [String] }
  :                                        { [] }
  | '(' Names ')'                          { reverse $2 }

Names :: { [String] }
  : ident                                  { [$1] }
  | Names ident                            { $2 : $1 }

Tests :: { [String] }
  :                                        { [] }
  | when Names                             { reverse $2 }

-- Accumulated in reverse, like 'Binders'. At least one: 'Rule' requires 'then'
-- and 'then' with nothing after it is a parse error rather than an empty body.
Body :: { [RawInstr] }
  : Instr                                  { [$1] }
  | Body ';' Instr                         { $3 : $1 }

Instr :: { RawInstr }
  : ident '=' Op                           { RawBind $1 $3 }
  | Op                                     { RawDo $1 }

-- One shape for every op: a word and whatever was written after it. Which op
-- the word names, and whether it was given the right arguments, is resolution's
-- (§2.5 — the parser is shallow).
Op :: { RawOp }
  : ident Operands                         { RawOp $1 (reverse $2) }

Operands :: { [RawOperand] }
  :                                        { [] }
  | Operands Operand                       { $2 : $1 }

Operand :: { RawOperand }
  : ident                                  { RawRef $1 }
  | num                                    { RawPos $1 }


Constraint :: { RawConstraint }
  : Binders '⊢' Term '≟' Term ':' Term   { RawConstraint (reverse $1) $3 $5 $7 }
  | '⊢' Term '≟' Term ':' Term           { RawConstraint [] $2 $4 $6 }

App :: { Raw }
  : App Atom                               { RawApp $1 $2 }
  | Atom                                   { $1 }

Atom :: { Raw }
  : ident                                  { RawName $1 }
  | univ                                   { RawUniverse $1 }
  | '(' Term ')'                           { $2 }

-- A possibly-empty run of atoms, accumulated in reverse like 'Binders'. An
-- 'elim''s three list-valued fields (§2.6, phase 7): each is parenthesized so
-- that a fixed field count and a fixed field order are the whole grammar, with
-- nothing left for a motive or a target to swallow by extending rightward the
-- way a λ or ∀ body does.
Atoms :: { [Raw] }
  :                                        { [] }
  | Atoms Atom                             { $2 : $1 }

-- Accumulated in reverse; the productions above put them back in order.
Binders :: { [RawBinder] }
  : Binder                                 { [$1] }
  | Binders Binder                         { $2 : $1 }

Binder :: { RawBinder }
  : '(' ident ':' Term ')'                 { RawBinder $2 $4 }

{

-- | Structured, per §12 invariant 2.
data ParseError
  = UnexpectedToken Pos Token
  | UnexpectedEndOfInput
  deriving (Eq, Show)

parseError :: [Located Token] -> Either ParseError a
parseError ts = Left $ case ts of
  Located p t : _ -> UnexpectedToken p t
  []              -> UnexpectedEndOfInput
}
