{
-- | The Happy grammar for the core and development languages (§2.6, §2.7).
--
-- Four start symbols rather than one, because the driver always knows which of
-- four things it is about to read and a single grammar covering all of them
-- would be ambiguous:
--
--   * 'parseTerm' — a term or a development, as a 'Raw' (§2.6).
--   * 'parseNameAndType' — @x : S@, for the commands that name a new binding.
--   * 'parseData' — a @data@ declaration, as a 'RawData' (§2.7, phase 6).
--   * 'parseEquation' — @Ξ ⊢ s ≟ t : T@, as a 'RawConstraint' (§3.3, phase 9).
--
-- Their types are generated by Happy from the @%name@ directives below, so
-- Haddock has nowhere to attach per-function documentation and reports this
-- module as under-documented. That is a property of the tool, not a gap.
--
-- The parser is deliberately shallow. It produces names, never resolved
-- variables, and it does no shape checking beyond what the grammar enforces —
-- both are "Thena.Syntax.Resolve"'s job (§2.5).
module Thena.Syntax.Parser
  ( -- * Errors
    ParseError (..)

    -- * Entry points
  , parseTerm
  , parseNameAndType
  , parseData
  , parseEquation
  , parseRule
  , parseRules
  , parseAtoms
  , parseEntry
  , parseInstralTy
  ) where

import Thena.Syntax.Concrete
  ( Raw (..)
  , RawBinder (..)
  , RawConstraint (..)
  , RawConstructor (..)
  , RawData (..)
  )
import Thena.Instral.Concrete (RawDecl (..), RawLanguage (..), RawProduction (..), RawGItem (..), RawFunction (..), RawRhs (..), RawBody (..), RawSignature (..), RawTy (..), RawRule (..), RawInstr (..), RawOp (..), RawOperand (..), RawTest (..))
import Thena.Syntax.Lexer (Located (..), Pos, Token (..))
}

%name parseTerm Term
%name parseNameAndType NameAndType
%name parseData Data
%name parseEquation Equation
%name parseRule Rule
%name parseRules RuleFile
%name parseAtoms AtomRun
-- **A whole REPL entry** (MS5 phase 70) — the same body a rule has, so a typed
-- entry and a rule body are one grammar and not two. **Since phase 78 it is the
-- same @Block@**, laid out by the same pass, so a multi-line entry separates its
-- instructions by the offside rule exactly as a rule file does.
%name parseEntry Block
-- **A written type** (MS5 phase 71) — what @:accepts@ and @:produces@ take.
%name parseInstralTy Ty
%tokentype { Located Token }
%monad { Either ParseError }
%error { parseError }

%token
  'λ'     { Located _ TLambda }
  '∀'     { Located _ TForall }
  '->'    { Located _ TArrow }
  '('     { Located _ TLParen }
  ')'     { Located _ TRParen }
  '{'     { Located _ TLBrace }
  '}'     { Located _ TRBrace }
  ';'     { Located _ TSemi }
  ':'     { Located _ TColon }
  '='     { Located _ TEquals }
  '?'     { Located _ TQuery }
  '≐'     { Located _ TGuessed }
  '▸'     { Located _ TPending }
  '⊢'     { Located _ TTurnstile }
  '≟'     { Located _ TEquate }
  '[|'    { Located _ TOpenQuote }
  tagopen  { Located _ (TTagOpen $$) }
  raw      { Located _ (TRaw $$) }
  tagclose { Located _ TTagClose }
  '|]'    { Located _ TCloseQuote }
  let     { Located _ TLet }
  in      { Located _ TIn }
  elim    { Located _ TElim }
  where   { Located _ TWhere }
  rule    { Located _ TRule }
  do      { Located _ TDo }
  language { Located _ TLanguage }
  when    { Located _ TWhen }
  then    { Located _ TThen }
  ':-'    { Located _ TNeck }
  num     { Located _ (TNumber $$) }
  str     { Located _ (TString $$) }
  chr     { Located _ (TChar $$) }
  '['     { Located _ TLBracket }
  ']'     { Located _ TRBracket }
  ','     { Located _ TComma }
  univ    { Located _ (TUniverse $$) }
  Type    { Located _ TUniverseOpen }
  ident   { Located _ (TIdent $$) }

%right '->'

%%

Term :: { Raw }
  : 'λ' Binders '->' Term                          { RawLam (reverse $2) $4 }
  | '∀' Binders '->' Term                          { RawPi (reverse $2) $4 }
  | let ident '=' Term ':' Term in Term            { RawLet $2 $4 $6 $8 }
  | let '?' ident ':' Term in Term                 { RawClaim $3 $5 $7 }
  | let '?' ident ':' Term '≐' '(' Term ')' in Term
                                                   { RawGuess $3 $5 $8 $11 }
  | Constraint '▸' Term                            { RawPending $1 $3 }
  -- **Level arguments are written or omitted** (MS3 phase 31c). Omitting them
  -- is the only spelling for a monomorphic family, which is every family
  -- written before this phase, so nothing existing moves.
  | elim ident '(' Atoms ')' Atom '(' Atoms ')' '(' Atoms ')' Atom
      { RawElim $2 [] (reverse $4) $6 (reverse $8) (reverse $11) $13 }
  | elim ident LevelArgs '(' Atoms ')' Atom '(' Atoms ')' '(' Atoms ')' Atom
      { RawElim $2 $3 (reverse $5) $7 (reverse $9) (reverse $12) $14 }
  | App '->' Term                                  { RawArrow $1 $3 }
  | App                                            { $1 }

-- The argument of @:convert@ (§9, phase 8). Two terms and the @≟@ that §2.7
-- already spells a constraint's two sides with, so the separator is not a new
-- piece of notation — it is the one the user chose for exactly this question,
-- asked without a context or a type.
Equation :: { (Raw, Raw) }
  : Term '≟' Term                          { ($1, $3) }

-- The argument of @assume@ and @claim@ (§2.4's "commands are the op vocabulary
-- spelled out"). The nameless form is the one that makes the op ask (§7.5).
NameAndType :: { (Maybe String, Raw) }
  : ident ':' Term                         { (Just $1, $3) }
  | ':' Term                               { (Nothing, $2) }


-- The argument of @data@ (§2.7's grammar, extended; decided by the user
-- planning phase 6). @data@ itself is not a token: the driver splits the first
-- word off the line before the lexer sees anything, which is what keeps @data@
-- a perfectly good identifier (§2.4).
--
-- Parameters are the binder groups left of the @:@; indices are the arrow
-- prefix of the type right of it, which must end in a universe. That is the
-- split §3.7 requires disambiguated, made syntactic.
Data :: { RawData }
  : ident MaybeBinders ':' Term where '{' Constructors '}'
                                           { RawData $1 (reverse $2) $4 (reverse $7) }

MaybeBinders :: { [RawBinder] }
  :                                        { [] }
  | Binders                                { $1 }

-- A datatype with no constructors is legal and useful: @Empty@ (§3.7).
Constructors :: { [RawConstructor] }
  :                                        { [] }
  | SomeConstructors                       { $1 }

SomeConstructors :: { [RawConstructor] }
  : Constructor                            { [$1] }
  | SomeConstructors ';' Constructor       { $3 : $1 }

Constructor :: { RawConstructor }
  : ident ':' Term                         { RawConstructor $1 $3 }

-- The rule language (§8, phase 21). @:-@ separates the head — the name and its
-- parameters — from the conditions and the body, and the space on either side
-- of it is deliberately unused: pattern matching on the focus and on the goal
-- is coming and will attach to the head (DECIDED by the user 2026-08-25).
--
-- @when@ is optional, because a rule may apply everywhere; @then@ is not,
-- because a rule with no body does nothing. Test words and op words are
-- @ident@s and not tokens — see 'Thena.Syntax.Concrete.RawRule'.
-- A whole rule-base file, less its header line. Rules may span lines — DECIDED
-- by the user 2026-08-25 — so the file is parsed whole rather than split, and
-- what ends a rule is the next 'rule' keyword or the end of input. Nothing in
-- 'Instr' can begin with 'rule', so no terminator is needed.
-- **The file is one layout block** (MS5 phase 75). A declaration begins in
-- column 1 — his ruling, 2026-09-12 — and that is now said by the offside rule
-- rather than by a separator the driver inserts: "Thena.Surface.Layout" is run
-- over the token stream with a block already open at column 1, so a declaration
-- at that column gets a @;@ and anything indented past it is a continuation.
--
-- **@separated@ and @TDeclSep@ are gone with it**, and so is the laxity they
-- left: a line beginning @;@ in column 1 used to be accepted in silence, and is
-- now what it looks like, an empty declaration.
RuleFile :: { [RawDecl] }
  : '{' Decls '}'                          { reverse $2 }

Decls :: { [RawDecl] }
  :                                        { [] }
  | Decl                                   { [$1] }
  | Decls ';' Decl                         { $3 : $1 }

Decl :: { RawDecl }
  : Rule                                   { DeclRule $1 }
  | Signature                              { DeclSignature $1 }
  | Function                               { DeclFunction $1 }
  | Language                               { DeclLanguage $1 }

Rule :: { RawRule }
  : rule ident Params ':-' Tests then Block  { RawRule $2 (reverse $3) $5 (reverse $7) }

-- **A body is a block** (MS5 phase 75). @then@ is a layout keyword, so
-- "Thena.Surface.Layout" inserts these braces where the offside rule says they
-- belong and a file that writes them itself passes through untouched — the same
-- bargain the surface language struck at MS4 phase 40, and his condition:
-- /"if implicit works, explicit has to work too."/
Block :: { [RawInstr] }
  : '{' Body '}'                           { $2 }

-- **A signature is its own declaration** (MS5 phase 67, his choice) — one line,
-- anywhere in the file, naming a callable and giving its whole type including
-- the result. A callable has several clauses and one type, which is why it does
-- not hang off a clause.
-- **A global function, and it needs no keyword of its own** — his choice,
-- 2026-09-12. Since MS5 phase 74 neither does a signature, so a declaration
-- beginning with a plain word is one of the two and the token after the name
-- tells them apart: @=@ or another parameter here, @:@ there.
Function :: { RawFunction }
  : ident Params '=' FunBody               { RawFunction $1 (reverse $2) $4 }

-- **A body is one expression or a @do@ block** (MS5 phase 75b, his choice of
-- opener). @do@ is already a layout keyword, so the block's braces come from
-- the offside rule and a one-line @do { a ; b }@ works too.
FunBody :: { RawBody }
  : Rhs                                    { BodyRhs $1 }
  | do Block                               { BodyBlock (reverse $2) }

-- What stands right of an @=@, here and in a body: an op application, or a
-- value written down. The second case excludes a bare @ident@ — @x = y@ is a
-- call to @y@, which is the reading it has always had.
Rhs :: { RawRhs }
  : Op                                     { RhsOp $1 }
  | ValueOperand                           { RhsValue $1 }
  | Lambda                                 { RhsValue $1 }

-- @\ x y -> ‹expression›@ (MS5 phase 68b). @\@ and @λ@ are one token and both
-- were already lexed, so this costs no new syntax.
Lambda :: { RawOperand }
  : 'λ' Params '->' FunBody                { RawLambda (reverse $2) $4 }

-- **An object language's grammar** (MS5 phase 69). Braces and @where@ are
-- already tokens, so this costs one keyword and no punctuation.
Language :: { RawLanguage }
  : language ident where '{' Prods '}'     { RawLanguage $2 (reverse $5) }

Prods :: { [RawProduction] }
  : Prod                                   { [$1] }
  | Prods ';' Prod                         { $3 : $1 }

Prod :: { RawProduction }
  : ident ':' GItems                       { RawProduction $1 (reverse $3) }

GItems :: { [RawGItem] }
  :                                        { [] }
  | GItems GItem                           { $2 : $1 }

GItem :: { RawGItem }
  : str                                    { GTerminal $1 }
  | ident                                  { GWord $1 }

-- **No keyword** (MS5 phase 74, his ruling). A declaration beginning with a
-- plain word is a signature or a function, and the token after the name says
-- which: @:@ for a signature, another name or @=@ for a function. That is one
-- token of lookahead, which is what an LALR parser has, so the two productions
-- share their @ident@ and part on the next token with no conflict.
Signature :: { RawSignature }
  : ident ':' Ty                           { RawSignature $1 $3 }

-- The type syntax. @->@ is already @%right@, so the chain nests to the right
-- and the last link is the result.
--
-- **A constructor may take arguments and a variable may not**, so an
-- application is @ident@ followed by a run of atoms and a bare @Core@ is that
-- run being empty. Writing it as one production is what keeps the grammar free
-- of a conflict between @Core@ and @List a@; whether the name takes the number
-- of arguments it was given is 'Thena.Rules.resolveTy'\'s question.
Ty :: { RawTy }
  : TyApp '->' Ty                          { RawTyArrow $1 $3 }
  | TyApp                                  { $1 }

TyApp :: { RawTy }
  : ident TyAtoms                          { RawTyCon $1 (reverse $2) }
  | TyParen                                { $1 }

TyAtoms :: { [RawTy] }
  :                                        { [] }
  | TyAtoms TyAtom                         { $2 : $1 }

TyAtom :: { RawTy }
  : ident                                  { RawTyCon $1 [] }
  | TyParen                                { $1 }

TyParen :: { RawTy }
  : '(' ')'                                { RawTyUnit }
  -- **The parentheses are kept** (2026-09-12) — see 'RawTyGroup'. Without
  -- them @a -> (b -> c)@ and @a -> b -> c@ are one tree, so a signature could
  -- not name a function result.
  | '(' Ty ')'                             { RawTyGroup $2 }
  | '(' Ty ',' Ty ')'                      { RawTyPair $2 $4 }

-- Parameters are a bare run of names, ended by @:-@ — no parentheses and no
-- commas. CORRECTED by the user 2026-08-25, planning phase 23: a call site
-- writes its arguments as every other op writes them, @call f x y@, so a
-- definition that wrapped its parameters would have been the odd one out.
Params :: { [String] }
  :                                        { [] }
  | Params ident                           { $2 : $1 }

-- A head is a run of tests with nothing between them, so a test that takes
-- operands is parenthesised — @when focus-is-hole (surface-is-name t)@ — and a
-- bare word is a test of no operands (MS4 phase 47). Without the brackets
-- @when focus-is-hole goal-type-is-pi@ would parse as one test applied to
-- another word, which is the same ambiguity a REPL argument run has and is
-- answered the same way.
Tests :: { [RawTest] }
  :                                        { [] }
  | when TestRun                           { reverse $2 }

TestRun :: { [RawTest] }
  : Test                                   { [$1] }
  | TestRun Test                           { $2 : $1 }

Test :: { RawTest }
  : ident                                  { RawTest $1 [] }
  | '(' ident Operands ')'                 { RawTest $2 (reverse $3) }

-- Accumulated in reverse, like 'Binders'.
--
-- **A body may be empty** (MS4 phase 49), where until then @then@ with nothing
-- after it was a parse error. §8 refused one on the argument that /a rule with
-- no body does nothing/, and the surface language's own @_@ is the
-- counterexample: @E⟦_⟧@ /is/ do nothing — his /"those elaborate just by not
-- elaborating"/. A clause that does nothing and a clause that does not match
-- are different answers, so an empty body says something.
--
-- @then@ stays required, so a rule still says where its body begins.
Body :: { [RawInstr] }
  :                                        { [] }
  | Instr                                  { [$1] }
  | Body ';' Instr                         { $3 : $1 }
  -- **A trailing @;@ is allowed** (MS5 phase 78). Without it @h = here ;@ —
  -- which phase 70 read as /more is coming/ and phase 78 no longer does — is a
  -- parse error whose message names the @}@ layout inserted at end of input,
  -- at position @0:0@: a brace the author never wrote, at a place that is not
  -- in their file. Haskell tolerates the same thing for the same reason.
  | Body ';'                               { $1 }

Instr :: { RawInstr }
  : ident '=' Rhs                          { RawBind $1 $3 }
  -- **A local's type, written as its own line** (MS5 phase 77) — the same
  -- spelling a declaration uses one level up, and told from a binding by the
  -- token after the name exactly as a signature is told from a function.
  | ident ':' Ty                           { RawAnnot $1 $3 }
  | Op                                     { RawDo $1 }

-- One shape for every op: a word and whatever was written after it. Which op
-- the word names, and whether it was given the right arguments, is resolution's
-- (§2.5 — the parser is shallow).
Op :: { RawOp }
  : ident Operands                         { RawOp $1 (reverse $2) }

-- | A REPL line's arguments (MS5 phase 62b) — the same run of operands a rule
-- body writes after an op word, and its own start symbol because the driver has
-- already split the word off.
Operands :: { [RawOperand] }
  :                                        { [] }
  | Operands Operand                       { $2 : $1 }

Operand :: { RawOperand }
  : ident                                  { RawRef $1 }
  | ValueOperand                           { $1 }

-- Every operand but a bare name. Split out at MS5 phase 68a so that the right
-- of an @=@ can take one without @x = y@ becoming ambiguous — it is a call.
ValueOperand :: { RawOperand }
  : '(' ident Operands ')'                 { RawNested $2 (reverse $3) }
  -- **A lambda in an argument takes parentheses**, like every other compound
  -- argument (§6.0.1); bare, it is what stands right of an @=@.
  | '(' Lambda ')'                         { $2 }
  | num                                    { RawPos $1 }
  | str                                    { RawText $1 }
  | chr                                    { RawChar $1 }
  | '[' ']'                                { RawList [] }
  | '[' Elements ']'                       { RawList (reverse $2) }
  | '(' Operand ',' Operand ')'            { RawPairOf $2 $4 }
  | '[|' Term '|]'                         { RawQuoted $2 }
  | tagopen raw tagclose                   { RawRegion $1 $2 }
  | tagopen tagclose                       { RawRegion $1 "" }


Elements :: { [RawOperand] }
  : Operand                                { [$1] }
  | Elements ',' Operand                   { $3 : $1 }

Constraint :: { RawConstraint }
  : Binders '⊢' Term '≟' Term ':' Term   { RawConstraint (reverse $1) $3 $5 $7 }
  | '⊢' Term '≟' Term ':' Term           { RawConstraint [] $2 $4 $6 }

App :: { Raw }
  : App Atom                               { RawApp $1 $2 }
  | Atom                                   { $1 }

Atom :: { Raw }
  : ident                                  { RawName $1 }
  -- **The corners are an atom, not a term** (phase 38). They were a @Term@
  -- production, so @⌜ t ⌝@ could not appear in an atom run — and phase 38's
  -- REPL writes every core argument of a rule exactly there. Moving it is
  -- strictly more permissive: every place it parsed before still reaches it
  -- through @Term -> App -> Atom@.
  | '[|' Term '|]'                         { RawQuote $2 }
  | ident LevelArgs                        { RawAt $1 $2 }
  | univ                                   { RawUniverse $1 }
  | Type                                   { RawUniverseOpen }
  | '(' Term ')'                           { $2 }

-- | @{ ℓ 0 }@ — a brace-enclosed run of level atoms, no commas, exactly as
-- rule parameters and call arguments are a bare run of names (phase 23).
LevelArgs :: { [Int] }
  : '{' LevelAtoms '}'                     { reverse $2 }

LevelAtoms :: { [Int] }
  :                                        { [] }
  | LevelAtoms LevelAtom                   { $2 : $1 }

LevelAtom :: { Int }
  : num                                    { $1 }

-- The argument list of a rule invoked at the REPL (phase 23b): a run of atoms,
-- exactly as a rule body writes its operands. @try (\ x -> x)@ is one argument
-- and @f a b@ is two, which is what makes a REPL line mean what the same line
-- means inside a rule body.
AtomRun :: { [Raw] }
  : Atoms                                  { reverse $1 }

-- A possibly-empty run of atoms, accumulated in reverse like 'Binders'. An
-- 'elim''s three list-valued fields (§2.6, phase 7): each is parenthesized so
-- that a fixed field count and a fixed field order are the whole grammar, with
-- nothing left for a motive or a target to swallow by extending rightward the
-- way a λ or ∀ body does.
Atoms :: { [Raw] }
  :                                        { [] }
  | Atoms Atom                             { $2 : $1 }

-- Accumulated in reverse; the productions above put them back in order.
Binders :: { [RawBinder] }
  : Binder                                 { [$1] }
  | Binders Binder                         { $2 : $1 }

Binder :: { RawBinder }
  : '(' ident ':' Term ')'                 { RawBinder $2 $4 }

{

-- | Structured, per §12 invariant 2.
data ParseError
  = UnexpectedToken Pos Token
  | UnexpectedEndOfInput
  deriving (Eq, Show)

parseError :: [Located Token] -> Either ParseError a
parseError ts = Left $ case ts of
  Located p t : _ -> UnexpectedToken p t
  []              -> UnexpectedEndOfInput


}
